apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: graylog-eck 
nodes:
- role: control-plane
- role: worker
  labels:
    nodeType: worker
- role: worker
  labels:
    nodeType: worker
- role: worker
  labels:
    nodeType: worker

