apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: graylog
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
        - name: graylog
          image: graylog/graylog:5.2.4
          env:
            - name: GRAYLOG_PASSWORD_SECRET
              value: somepasswordpepper
            # echo -n "Enter Password: " && head -1 < /dev/stdin | tr -d '\n' | sha256sum | cut -d " " -f1
            # somepasswordpepper
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: 415e8a6ba1c3eb93e81df34731acc3d60efee685c8e6f7412592a45ba3a0e3b0
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: http://127.0.0.1:9000/
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-graylog-es-elastic-user
                  key: elastic
            - name: GRAYLOG_ELASTICSEARCH_HOSTS
              value: http://elastic:$(ELASTICSEARCH_PASSWORD)@es-graylog-es-http:9200
            - name: GRAYLOG_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-graylog-graylog-graylog
                  key: connectionString.standardSrv
          ports:
          - name: web
            containerPort: 9000
            protocol: TCP
          - name: syslog-tcp
            containerPort: 1514
            protocol: TCP
          - name: syslog-udp
            containerPort: 1514
            protocol: UDP
          - name: gelf-tcp
            containerPort: 12201
            protocol: TCP
          - name: gelf-udp
            containerPort: 12201
            protocol: UDP
